### ISSUE TITLE
Hi can I use these project for my project 

### ISSUE THREAD

**Issue by safeeraliPS** [dev-mgkaung/FaceBookHDVideoDownloader#2]
Can I use these project for my project and post to playstore

**Comment by dev-mgkaung** [comment]
Yes sure you can do it.  But take care because playstore policy is resticted facebook video downloader app.

**Comment by safeeraliPS** [comment]
Your project have vires on your library google decorated and suspended my
app

**Comment by safeeraliPS** [comment]
Google is dectacted a virus library on your application so google suspended
application
